# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f005ae429dae0c888f3cf6fd9755de2f6eafe4934fbcb3002bd3bb9cc1259518cd825080560fe5a0aab57d2b60d1a63335fb8382f54f3c75544ef4c290b92c1a

test:
  secret_key_base: afbb2ba181946c28b4ac504c9b58a63a7cb7a2433bcbc20fea91cfd1353312cf7c2b96d9848199c70f60d0ec0ae91669389dfe51e4cbe7ac93f39d37d0e71a9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
